def printProblem():
    print("Problem #12 [Hard]\n"
            "This problem was asked by Amazon.\n"
            "There exists a staircase with N steps, and you can climb up\n"
            "either 1 or 2 steps at a time. Given N, write a function that\n"
            "returns the number of unique ways you can climb the staircase.\n"
            "The order of the steps matters.\n"
            "For example, if N is 4, then there are 5 unique ways:\n"
            "1, 1, 1, 1\n"
            "2, 1, 1\n"
            "1, 2, 1\n"
            "1, 1, 2\n"
            "2, 2\n"
            "What if, instead of being able to climb 1 or 2 steps at a time,\n"
            "you could climb any number from a set of positive integers X?\n"
            "For example, if X = {1, 3, 5}, you could climb 1, 3, or 5 steps\n"
            "at a time.")
