def printProblem():
    print("Each new term in the Fibonacci sequence is generated by adding\n"
            "the previous two terms. By starting with 1 and 2, the first 10\n"
            "terms will be:\n"
            "  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
            "By considering the terms in the Fibonacci sequence whose values\n"
            "do not exceed four million, find the sum of the even-valued terms.")

def sumEvenFib(maxNum):
    a,b=1,2
    sum=0
    while b <= maxNum:
        if b%2==0:
            sum+=b
        temp=a
        a=b
        b=b+temp
    return sum

import unittest
class eu02Test(unittest.TestCase):
    def test_eu02(self):
        self.assertEqual(0,sumEvenFib(0))
        self.assertEqual(0,sumEvenFib(1))
        self.assertEqual(2,sumEvenFib(2))
        self.assertEqual(2,sumEvenFib(3))
        self.assertEqual(2,sumEvenFib(4))
        self.assertEqual(2,sumEvenFib(5))
        self.assertEqual(2,sumEvenFib(6))
        self.assertEqual(2,sumEvenFib(7))
        self.assertEqual(10,sumEvenFib(8))
        self.assertEqual(10,sumEvenFib(9))
        self.assertEqual(10,sumEvenFib(33))
        self.assertEqual(44,sumEvenFib(34))
        self.assertEqual(44,sumEvenFib(35))
        self.assertEqual(4613732,sumEvenFib(4000000))
if __name__=="__main__":
    unittest.main()
