#include <optional>
#include <memory>

#include <catch2/catch.hpp>

#include "utility.hpp"
#include "integer_container_impl.hpp"

/**
 * The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
 * - add your own custom tests
 * - delete existing tests
 * - modify test contents or expected output
 *
 * The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.
 *
 * The results of these tests do not affect the final score (unless the project fails to build).
 */
class SandboxTestsFixture {
 public:
  SandboxTestsFixture() = default;
 protected:

  std::shared_ptr<IntegerContainer> container = std::make_shared<IntegerContainerImpl>();
};

TEST_CASE_METHOD(SandboxTestsFixture, "Test sample") {
  Utility::CheckTimeout([&]() {
    REQUIRE(container->Add(5) == 1);
    REQUIRE(container->Add(10) == 2);
    REQUIRE(container->Add(5) == 3);
    REQUIRE(container->Delete(10));
    REQUIRE(!container->Delete(1));
    REQUIRE(container->Add(1) == 3);
  }, 100);
}
